channels:
- conda-forge
dependencies:
- python=3.7
- pip:
  - azureml-sdk
  - azureml-widgets
  - scikit-learn
  - numpy
  - tensorflow-gpu==2.4.0
  - matplotlib
  - scikit-image
  - Pillow
  - opencv-contrib-python-headless
  - mtcnn
